"""add items and history tables

Revision ID: 6232436391d8
Revises: cbae445e255a
Create Date: 2026-05-20 20:55:53.471495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6232436391d8'
down_revision: Union[str, Sequence[str], None] = 'cbae445e255a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licitacao_historico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('licitacao_id', sa.UUID(), nullable=False),
    sa.Column('status_anterior', sa.String(), nullable=True),
    sa.Column('status_novo', sa.String(), nullable=False),
    sa.Column('data_mudanca', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licitacao_itens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('licitacao_id', sa.UUID(), nullable=False),
    sa.Column('numero_item', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('unidade_medida', sa.String(), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licitacao_itens')
    op.drop_table('licitacao_historico')
    # ### end Alembic commands ###
