"""create licitacoes table

Revision ID: 62f390fa0a03
Revises: 
Create Date: 2026-05-19 23:13:31.537753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f390fa0a03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licitacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_pncp', sa.String(), nullable=False),
    sa.Column('orgao_nome', sa.String(), nullable=False),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('valor_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(), nullable=True),
    sa.Column('data_fim_propostas', sa.DateTime(), nullable=True),
    sa.Column('link_origem', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacoes_id_pncp'), 'licitacoes', ['id_pncp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licitacoes_id_pncp'), table_name='licitacoes')
    op.drop_table('licitacoes')
    # ### end Alembic commands ###
