"""consolidated initial migration

Revision ID: d7d269352a93
Revises: 
Create Date: 2026-05-20 21:27:48.770238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7d269352a93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licitacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_pncp', sa.String(), nullable=False),
    sa.Column('orgao_nome', sa.String(), nullable=False),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('valor_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(), nullable=True),
    sa.Column('data_fim_propostas', sa.DateTime(), nullable=True),
    sa.Column('link_origem', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacoes_id_pncp'), 'licitacoes', ['id_pncp'], unique=True)
    op.create_table('licitacao_historico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('licitacao_id', sa.UUID(), nullable=False),
    sa.Column('status_anterior', sa.String(), nullable=True),
    sa.Column('status_novo', sa.String(), nullable=False),
    sa.Column('data_mudanca', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licitacao_itens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('licitacao_id', sa.UUID(), nullable=False),
    sa.Column('numero_item', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('unidade_medida', sa.String(), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('licitacao_id', 'numero_item', name='uq_licitacao_item_numero')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licitacao_itens')
    op.drop_table('licitacao_historico')
    op.drop_index(op.f('ix_licitacoes_id_pncp'), table_name='licitacoes')
    op.drop_table('licitacoes')
    # ### end Alembic commands ###
